// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnjfocZqMhV-du6ELFmW2t1eYcAjiUH8E',
    appId: '1:409724060713:web:60288a7f2840ecfa6d8838',
    messagingSenderId: '409724060713',
    projectId: 'conectapro-ff6d5',
    authDomain: 'conectapro-ff6d5.firebaseapp.com',
    storageBucket: 'conectapro-ff6d5.firebasestorage.app',
    measurementId: 'G-MRF9CDPLPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxzjKBnukUuZ8usOHGvM5TSxjZwpUjdzU',
    appId: '1:409724060713:android:87173ae39d2f209c6d8838',
    messagingSenderId: '409724060713',
    projectId: 'conectapro-ff6d5',
    storageBucket: 'conectapro-ff6d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPLuxpmzosKasvttTWThbP_mGJmRxqERQ',
    appId: '1:409724060713:ios:83fae9e4eea0d0136d8838',
    messagingSenderId: '409724060713',
    projectId: 'conectapro-ff6d5',
    storageBucket: 'conectapro-ff6d5.firebasestorage.app',
    iosBundleId: 'com.example.conectapro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPLuxpmzosKasvttTWThbP_mGJmRxqERQ',
    appId: '1:409724060713:ios:83fae9e4eea0d0136d8838',
    messagingSenderId: '409724060713',
    projectId: 'conectapro-ff6d5',
    storageBucket: 'conectapro-ff6d5.firebasestorage.app',
    iosBundleId: 'com.example.conectapro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnjfocZqMhV-du6ELFmW2t1eYcAjiUH8E',
    appId: '1:409724060713:web:223e72d38743596f6d8838',
    messagingSenderId: '409724060713',
    projectId: 'conectapro-ff6d5',
    authDomain: 'conectapro-ff6d5.firebaseapp.com',
    storageBucket: 'conectapro-ff6d5.firebasestorage.app',
    measurementId: 'G-L2G17WKL1H',
  );
}
